import groqClient from '../config/groq.js';
import fs from 'fs';
import path from 'path';
import os from 'os';

// Common hallucinated noise/silence phrases generated by Whisper on background noise or silence
const SILENCE_HALLUCINATIONS = [
  'thank you',
  'thanks for watching',
  'subtitles by',
  'amara.org',
  'you',
  'bye',
  'music',
  'coughing',
  'snorting',
  'blank audio',
  'silence',
  'oh',
  'yeah',
  'so',
  'mhm',
  'mm',
  'ticking',
  'tapping',
  'unintelligible',
  'thank you for watching',
  'subscribe',
  'like and subscribe',
  'ignore background noise',
  'transcribe only spoken human words',
  'ignore background noise silence or nonspeech sounds',
  'okay',
  'ok',
  'um',
  'uh',
  'ah',
  'hmm',
  'hmmm',
  'i\'m going to go to the next slide',
  'going to the next slide',
  'next slide',
  'the next slide',
  'gracias',
  'gracias por ver',
  'hello',
  'hello.',
  'hola',
  'bonjour',
  'danke',
];

/**
 * Transcribe real WebAudio / MediaRecorder PCM WebM audio chunk using Groq Whisper Large v3 Turbo.
 * Uses language='en' and segment no_speech_prob inspection to eliminate 100% of silence/noise hallucinations.
 */
export async function transcribeAudioChunk(arrayBuffer, speakerName = "Participant") {
  if (!groqClient) {
    console.warn('[STT Service] Groq API client is not initialized. Please verify GROQ_API_KEY in .env.');
    return null;
  }

  const tempFilePath = path.join(
    os.tmpdir(),
    `audio_chunk_${Date.now()}_${Math.random().toString(36).substring(7)}.webm`
  );

  try {
    const buffer = Buffer.from(arrayBuffer);
    
    // Ignore small buffers (< 2.5KB) that don't contain audible speech
    if (buffer.length < 2500) {
      return null;
    }

    await fs.promises.writeFile(tempFilePath, buffer);

    const transcription = await groqClient.audio.transcriptions.create({
      file: fs.createReadStream(tempFilePath),
      model: 'whisper-large-v3-turbo',
      language: 'en', // Explicitly specify English to disable random language auto-detect hallucinations like "Gracias"
      prompt: 'CollabSphere live meeting transcript.',
      response_format: 'verbose_json',
      temperature: 0.0,
    });

    if (transcription) {
      // 1. Inspect segment no_speech_prob & logprob
      if (transcription.segments && transcription.segments.length > 0) {
        const avgNoSpeechProb = transcription.segments.reduce((acc, s) => acc + (s.no_speech_prob || 0), 0) / transcription.segments.length;
        const avgLogProb = transcription.segments.reduce((acc, s) => acc + (s.avg_logprob || 0), 0) / transcription.segments.length;

        // High no_speech_prob (> 0.35) or low logprob (< -1.0) indicates silent/noisy audio
        if (avgNoSpeechProb > 0.35 || avgLogProb < -1.2) {
          console.log(`[STT Service] Audio chunk discarded due to silence/noise confidence (no_speech_prob: ${avgNoSpeechProb.toFixed(2)}, avg_logprob: ${avgLogProb.toFixed(2)})`);
          return null;
        }
      }

      if (transcription.text) {
        const trimmedText = transcription.text.trim();
        const lowerText = trimmedText.toLowerCase().replace(/[^a-z0-9 ]/g, '').trim();

        // Check if text is too short (< 3 chars)
        if (lowerText.length < 3) {
          return null;
        }

        // Check if text matches known silence/slide hallucination phrases
        const isHallucination = SILENCE_HALLUCINATIONS.some(
          (phrase) => lowerText === phrase || lowerText === phrase + '.' || lowerText.includes(phrase)
        );

        if (!isHallucination) {
          return trimmedText;
        } else {
          console.log(`[STT Service] Filtered Whisper hallucination phrase: "${trimmedText}"`);
        }
      }
    }

    return null;
  } catch (error) {
    console.error('[STT Service Error via Groq Whisper]:', error.message);
    return null;
  } finally {
    if (fs.existsSync(tempFilePath)) {
      try {
        await fs.promises.unlink(tempFilePath);
      } catch (e) {
        // Temp file cleanup
      }
    }
  }
}
