import groqClient from '../config/groq.js';
import fs from 'fs';
import path from 'path';
import os from 'os';

// Common hallucinated noise/silence phrases generated by Whisper on background noise or silence
const SILENCE_HALLUCINATIONS = [
  'thank you',
  'thanks for watching',
  'subtitles by',
  'amara.org',
  'you',
  'bye',
  'music',
  'coughing',
  'snorting',
  'blank audio',
  'silence',
  'oh',
  'yeah',
  'so',
  'mhm',
  'mm',
  'ticking',
  'tapping',
  'unintelligible',
  'thank you for watching',
  'subscribe',
  'like and subscribe',
  'ignore background noise',
  'transcribe only spoken human words',
  'ignore background noise silence or nonspeech sounds',
];

/**
 * Transcribe real WebAudio / MediaRecorder PCM WebM audio chunk using Groq Whisper Large v3 Turbo.
 * Returns the exact transcribed text spoken by the participant, or null if silent/no speech.
 */
export async function transcribeAudioChunk(arrayBuffer, speakerName = "Participant") {
  if (!groqClient) {
    console.warn('[STT Service] Groq API client is not initialized. Please verify GROQ_API_KEY in .env.');
    return null;
  }

  const tempFilePath = path.join(
    os.tmpdir(),
    `audio_chunk_${Date.now()}_${Math.random().toString(36).substring(7)}.webm`
  );

  try {
    const buffer = Buffer.from(arrayBuffer);
    
    // Ignore small buffers (< 2.5KB) that don't contain audible speech
    if (buffer.length < 2500) {
      return null;
    }

    await fs.promises.writeFile(tempFilePath, buffer);

    const transcription = await groqClient.audio.transcriptions.create({
      file: fs.createReadStream(tempFilePath),
      model: 'whisper-large-v3-turbo',
      prompt: 'CollabSphere live meeting transcript.',
      response_format: 'verbose_json',
      temperature: 0.0,
    });

    if (transcription && transcription.text) {
      const trimmedText = transcription.text.trim();
      const lowerText = trimmedText.toLowerCase().replace(/[^a-z0-9 ]/g, '').trim();

      // Check if text is too short or is a known silence/noise hallucination phrase
      if (lowerText.length < 3) {
        return null;
      }

      const isHallucination = SILENCE_HALLUCINATIONS.some(
        (phrase) => lowerText === phrase || lowerText === phrase + '.' || lowerText.includes(phrase)
      );

      if (!isHallucination) {
        return trimmedText;
      }
    }

    return null;
  } catch (error) {
    console.error('[STT Service Error via Groq Whisper]:', error.message);
    return null;
  } finally {
    if (fs.existsSync(tempFilePath)) {
      try {
        await fs.promises.unlink(tempFilePath);
      } catch (e) {
        // Temp file cleanup
      }
    }
  }
}
